FROM maven:3.9.0-eclipse-temurin-11
RUN mkdir /so
WORKDIR /so
COPY pom.xml /so
COPY cucumber-junit-examples/src /so/cucumber-junit-examples/src/
COPY cucumber-junit-examples/pom.xml /so/cucumber-junit-examples
COPY cucumber-testng-examples/src /so/cucumber-testng-examples/src/
COPY cucumber-testng-examples/pom.xml /so/cucumber-testng-examples
COPY junit4-examples/src /so/junit4-examples/src/
COPY junit4-examples/pom.xml /so/junit4-examples
COPY junit5-examples/src /so/junit5-examples/src/
COPY junit5-examples/pom.xml /so/junit5-examples
COPY testng-xml/src /so/testng-xml/src/
COPY testng-xml/pom.xml /so/testng-xml
# CMD mvn test -pl testng-xml -DtestngXmlFile=myDemoTests-LocalServer.xml -X
CMD curl http://localhost:4000/give_me_valid_username



