# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: TestNG XML Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Action Test
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          region: eu-central
          tunnel-name: eyalyovel_tunnel_name
      - name: Run tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          mvn test -pl testng-xml -DtestngXmlFile=myDemoTests-Desktop.xml -X
#          echo '::set-output name=SELECTED_COLOR::$(mvn test -pl testng-xml -DtestngXmlFile=myDemoTests-Desktop.xml -X)'
        id: random-color-generator
#      - name: Get color
#        env:
#          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
#          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
#        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"