# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: TestNG XML Tests CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
#    - name: Get env name
#      env:
#        MY_ENV: "Hello world"
#      run: echo "The ENV is $MY_ENV "
    - name: Run testng tests
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: |
        echo '::set-output name=RUN_TESTS::mvn test -pl testng-xml -DtestngXmlFile=myDemoTests-Desktop.xml -X'
#        mvn test -pl testng-xml -DtestngXmlFile=myDemoTests-Desktop.xml -X
        echo '::set-output name=RUN_TESTS2'
      id: run-sauce-tests
    - name: Get output
      run: |
        echo "The output is  ${{ steps.run-sauce-tests.outputs.RUN_TESTS }}"
        echo "The output is  ${{ steps.run-sauce-tests.outputs.RUN_TESTS2 }}"